[workspace]
members = [
  "fake_data_generator",
  "api",
  "ingestion"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
axum = "0.6.20"
bb8 = "0.8.1"
bb8-postgres = "0.8.1"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"] }
futures = "0.3.28"
http-body-util = "0.1.0"
hyper = { version = "1.1.0", features = [ "http1", "http2", "server" ] }
hyper-util = { version = "0.1.2", features = [ "full" ] }
postgres-types = { version = "0.2.6", features = ["derive", "with-chrono-0_4"] }
rand = "0.8.5"
rand_distr = "0.4.3"
regex = "1.10.2"
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
