[package]
name = "lard_ingestion"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytes. workspace = true
chrono.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
regex.workspace = true
tokio.workspace = true
