---
- name: Create ipalias network
  openstack.cloud.network:
    cloud: "{{ ostack_cloud }}"
    region_name: "{{ ostack_region }}"
    name: "{{ ipalias_network_name }}"
    external: false
    state: present
  run_once: true

- name: Create ipalias network subnet
  openstack.cloud.subnet:
    cloud: "{{ ostack_cloud }}"
    region_name: "{{ ostack_region }}"
    network_name: "{{ ipalias_network_name }}"
    name: "{{ ipalias_network_name }}-subnet"
    cidr: 192.168.20.0/24
    state: present
    dns_nameservers: "{{ met_dns[ostack_region] }}"
  run_once: true

- name: Connect ipalias network to public network
  openstack.cloud.router:
    cloud: "{{ ostack_cloud }}"
    region_name: "{{ ostack_region }}"
    state: present
    name: ipalias-router
    network: public
    interfaces:
      - "{{ ipalias_network_name }}-subnet"
  run_once: true

- name: Remove default gateway for subnet
  openstack.cloud.subnet:
    cloud: "{{ ostack_cloud }}"
    region_name: "{{ ostack_region }}"
    network_name: "{{ ipalias_network_name }}"
    name: "{{ ipalias_network_name }}-subnet"
    cidr: "{{ ipalias_ostack_network_cidr }}"
    no_gateway_ip: true
    state: present
  run_once: true
