[header]
# TODO: reconsider format of station/level/sensor filtering. Is this supposed to be a regex?
# Would we be better served with a blocklist/allowlist?
# stations = "*"
param_id = 211
time_resolution = "PT1H"
# level = "*"
sensor = [0]

[pipeline]
[[pipeline.step]]
name = "special_value_check"
[pipeline.step.special_value_check]
special_values = [-999999, -6999, -99.9, -99.8, 999, 6999, 9999]

[[pipeline.step]]
name = "range_check"
[pipeline.step.range_check]
min = -55
max = 50

# [[pipeline.step]]
# name = "climate_range_check"
# [pipeline.step.range_check_dynamic]
# source = "netcdf" # TODO: define a neat spec for this?

[[pipeline.step]]
name = "step_check"
[pipeline.step.step_check]
max = 18.6

[[pipeline.step]]
name = "flatline_check"
[pipeline.step.flatline_check]
max = 10

[[pipeline.step]]
name = "spike_check"
[pipeline.step.spike_check]
max = 18.6

# [[pipeline.step]]
# name = "model_consistency_check"
# [pipeline.step.model_consistency_check]
# model_source = "lustre"
# model_args = "arome/air_temperature" # TODO: verify if we need more args than this for the model
# threshold = 3.0 # FIXME: made up value by Ingrid
