---
- name: Add hostkey to localhost `known_hosts`
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    state: present
    # NOTE: requires `gather_facts: true`
    key: >
      "{{ ansible_host }}"
      ecdsa-sha2-nistp256
      "{{ ansible_ssh_host_key_ecdsa_public }}"
    hash_host: true
  delegate_to: localhost
