---
- name: Create mount point
  ansible.builtin.file:
    path: "{{ ostack_mount_point }}"
    state: directory
    owner: ubuntu # change to postgres?
    group: ubuntu # change to postgres?
    mode: 'u=rw,g=rws,o=r'
  become: true

- name: Create ext4 filesystem on mount device
  community.general.filesystem:
    dev: '{{ ostack_mount_device }}'
    fstype: ext4
  become: true

- name: Read device information (always use unit when probing)
  community.general.parted:
    device: '{{ ostack_mount_device }}'
    unit: MiB
  register: sdb_info
  become: true

- name: Print out the device information
  ansible.builtin.debug:
    msg: "Partitions {{ sdb_info.partitions }}"

# this also changes the fstab so its still there when rebooted!
- name: Mount the device on the mount point
  ansible.posix.mount:
    path: "{{ ostack_mount_point }}"
    src: '{{ ostack_mount_device }}'
    fstype: ext4
    state: mounted
  become: true

- name: Fetch the UUID of mounted device
  ansible.builtin.command: blkid --match-tag UUID --output value '{{ ostack_mount_device }}'
  changed_when: false
  register: blkid_cmd
  become: true

- name: Print out the UUID
  ansible.builtin.debug:
    msg: "UUID {{ blkid_cmd.stdout }}"
