---
- name: Check cluster
  ansible.builtin.command: repmgr -f /etc/repmgr.conf cluster show
  become: true
  become_user: postgres
  register: cluster_status
  changed_when: false
  tags: [never, debug]

  # TODO: check that primary says "unreachable"?
- name: Print cluster status
  ansible.builtin.debug:
    msg: "{{ cluster_status }}"
  tags: [never, debug]

- name: Dry run of standby promotion
  ansible.builtin.command: repmgr -f /etc/repmgr.conf standby promote --dry-run
  become: true
  become_user: postgres
  changed_when: false
  register: dry_run_promote

- name: Print result of dry-run
  ansible.builtin.debug:
    msg: "{{ dry_run_promote }}"
  tags: [never, debug]

# TODO: should postgres service be restarted?
# TODO: check that primary says "failed"?
- name: Promote standby
  ansible.builtin.command: repmgr -f /etc/repmgr.conf standby promote
  become: true
  become_user: postgres
  changed_when: true

# TODO: should this happen before or after rejoining the old primary?
# TODO: should this be done immediately after promoting the standby?
- name: Start LARD ingestion service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: lard_ingestion
    state: restarted
    enabled: true
  become: true
