---
- name: Create lard group
  ansible.builtin.group:
    name: lard
    state: present
  become: true

- name: Create lard user
  ansible.builtin.user:
    name: lard
    groups: lard
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false
  become: true

- name: Copy files to server
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    # TODO: should these belong to 'lard'?
    owner: root
    group: root
  become: true
  loop:
    # TODO: these permissions are probably wrong?
    - src: lard_ingestion.service
      dest: /etc/systemd/system
      mode: "0664"
    - src: var_file
      dest: /etc/systemd/lard_ingestion.var
      mode: "0600"
    - src: "{{ playbook_dir }}/../target/release/lard_ingestion"
      dest: /usr/local/bin
      mode: "0755"
    - src: "{{ playbook_dir }}/../ingestion/resources"
      dest: /usr/local/bin
      mode: "0755"

- name: Start LARD ingestion service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: lard_ingestion
    state: restarted
    enabled: true
  become: true
