---
- name: Create lard group
  ansible.builtin.group:
    name: lard
    state: present

- name: Create lard user
  ansible.builtin.user:
    name: lard
    groups: lard
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

# TODO: should we deploy in non root user?
- name: Copy files to server
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  become: true
  loop: "{{ deploy_files }}"

- name: Import environment variables # noqa: command-instead-of-module
  ansible.builtin.command: systemctl import-environment LARD_CONN_STRING STINFO_CONN_STRING
  # TODO: ansible docs say that 'environment:' is "not a recommended way to pass in confidential data."
  environment: "{{ deploy_envars }}"
  become: true
  changed_when: false

- name: Start LARD ingestion service
  ansible.builtin.systemd:
    daemon_reload: true
    name: lard_ingestion
    state: restarted
    enabled: true
  become: true

- name: Unset environment variables # noqa: command-instead-of-module
  ansible.builtin.command: systemctl unset-environment LARD_CONN_STRING STINFO_CONN_STRING
  become: true
  changed_when: false
