---
- name: Create what is needed for the bigip load balancers
  hosts: servers
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Bigip
      ansible.builtin.import_role:
        name: pg
        tasks_from: bigip.yml
      vars:
        pg_version: 17
