---
- name: Configure VMs for replication
  hosts: servers
  remote_user: ubuntu
  gather_facts: true
  # TODO: it would be nice to have a host (dns?)
  # that always points to the primary
  vars:
    primary: lard-a # or provide via cmd '-e primary=...'

  roles:
    - role: ssh
    - role: pg
      vars:
        pg_version: 17
        pg_primary_ip: "{{ hostvars[primary].ansible_host }}"
        pg_mount_point: "{{ ostack_mount_point }}"
