---
- name: Configure VMs
  hosts: servers
  remote_user: ubuntu
  gather_facts: true
  vars:
    primary: lard-a # or provide via cmd
    db_password: # provide via cmd
    repmgr_password: # provide via cmd

  tasks:
    - name: Add keys to local known_hosts
      ansible.builtin.include_role:
        name: ssh
        tasks_from: localhost.yml

    - name: Add user SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: users.yml

    - name: Format VM
      ansible.builtin.include_role:
        name: ostack
        tasks_from: vm_format.yml
      vars:
        ostack_repmgr_password: "{{ repmgr_password }}"

    - name: Share postgres SSH key between hosts
      ansible.builtin.include_role:
        name: ssh
        tasks_from: postgres.yml

    - name: Setup primary node
      ansible.builtin.include_role:
        name: ostack
        tasks_from: create_primary.yml
      when: inventory_hostname == primary
      vars:
        ostack_db_password: "{{ db_password }}"

    - name: Setup standby node(s)
      ansible.builtin.include_role:
        name: ostack
        tasks_from: create_standby.yml
      when: inventory_hostname != primary
      vars:
        ostack_primary_ip: "{{ hostvars[primary].ansible_host }}"
