---
- name: Mount disks and install stuff on the VMs
  hosts: servers
  remote_user: ubuntu
  gather_facts: false
  vars:
    primary: lard-a
    ostack_primary_floating_ip: # provide via cmd
    ostack_db_password: # provide via cmd
    ostack_repmgr_password: # provide via cmd

  tasks:
    - name: Add user SSH keys
      ansible.builtin.include_role:
        name: ssh
        tasks_from: users.yml

    - name: Format VM
      ansible.builtin.include_role:
        name: ostack
        tasks_from: vm_format.yml

    - name: Share postgres SSH key between hosts
      ansible.builtin.include_role:
        name: ssh
        tasks_from: postgres.yml

    - name: Setup primary host
      ansible.builtin.include_role:
        name: ostack
        tasks_from: create_primary.yml
      when: inventory_hostname == primary

    - name: Setup standby host
      ansible.builtin.include_role:
        name: ostack
        tasks_from: create_standby.yml
      vars:
        ostack_primary_host_ip: "{{ hostvars[primary].ansible_host }}"
      when: inventory_hostname != primary
