---
# TODO: update this when we change file names in db directory
- name: Perform DB migration
  hosts: servers
  remote_user: ubuntu
  gather_facts: false
  vars:
    # TODO: is there a better way to get this fact automatically?
    primary: lard-a # or provide via cmd

  tasks:
    - name: Copy the db folder to the remote
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../db/"
        dest: /etc/postgresql/16/db/
        mode: "0755"
      become: true

    - name: Update schema in lard
      community.postgresql.postgresql_script:
        db: lard
        path: "/etc/postgresql/16/db/{{ item }}"
      loop:
        - public.sql
        - partitions_generated.sql
      become: true
      become_user: postgres
      when: inventory_hostname == primary
