---
# TODO: update this when we change file names in db directory
- name: Perform DB migration
  # TODO: we should have a host that always points to the primary
  hosts: "{{ primary }}"
  remote_user: ubuntu
  gather_facts: false
  vars:
    primary: lard-a # or provide via cmd

  tasks:
    - name: Copy and run
      ansible.builtin.import_role:
        name: pg
        tasks_from: migration.yml
      vars:
        pg_mount_point: "{{ ostack_mount_point }}"
