---
- name: Provision
  hosts: servers
  gather_facts: false
  vars:
    ostack_vm_key_name: # provide via cmd

  tasks:
    - name: Setup networks
      ansible.builtin.include_role:
        name: ostack
        tasks_from: networks.yml
      delegate_to: localhost
      run_once: true

    - name: Create VMs
      ansible.builtin.include_role:
        name: ostack
        tasks_from: vm_create.yml
      delegate_to: localhost
