---
- name: Provision
  hosts: servers
  gather_facts: false
  vars:
    key_name: # provide via cmd

  tasks:
    - name: Setup networks # noqa run-once
      ansible.builtin.include_role:
        name: ostack
        tasks_from: networks.yml
        apply:
          delegate_to: localhost
      run_once: true
      tags:
        - network

    - name: Create VMs
      ansible.builtin.include_role:
        name: ostack
        tasks_from: vm_create.yml
        apply:
          delegate_to: localhost
      vars:
        ostack_vm_key_name: "{{ key_name }}"
