---
- name: Provision 1
  hosts: localhost
  gather_facts: false
  tags:
    - network
  tasks:
    - name: Setup networks
      ansible.builtin.include_role:
        name: ostack
        tasks_from: networks.yml

- name: Provision 2
  hosts: servers
  gather_facts: false
  vars:
    key_name: # provide via cmd
  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: ostack
        tasks_from: vm_create.yml
        apply:
          delegate_to: localhost
      vars:
        ostack_vm_key_name: "{{ key_name }}"
