---
- name: Preliminary setup
  hosts: localhost
  gather_facts: false
  vars:
    # set here or provide via cmd '-e ostack_key_name=... -e ostack_key_file=...'
    ostack_key_name: # label for the key to set up on Ostack
    ostack_key_file: # key file containing the your ssh key
  tasks:
    - name: Key pair
      ansible.builtin.include_role:
        name: ostack
        tasks_from: keypair.yml
      tags: addkey

    - name: Project network
      ansible.builtin.include_role:
        name: ostack
        tasks_from: network.yml
      tags: network

- name: Provision
  hosts: servers
  gather_facts: false
  vars:
    # set here or provide via cmd, '-e ostack_key_name=...'
    ostack_key_name: # label for the key on Ostack to use to create the VMs
  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: ostack
        tasks_from: create_vm.yml
        apply:
          delegate_to: localhost
      tags: vm
