---
- name: Setup networks and 2 vms
  vars:
    ostack_cloud: lard
    ipalias_network_name: ipalias
    ostack_region: Ostack2-EXT
  hosts: localhost
  gather_facts: false

  roles:
    - role: networks
    - role: vm # in A
      vars:
        vm_name: lard-a
        vm_availability_zone: ext-a
        vm_ip: '{{ hostvars[groups["servers"][0]].ansible_host }}'
    - role: vm # in B
      vars:
        vm_name_stuff: lard-b
        vm_availability_zone: ext-b
        vm_ip: '{{ hostvars[groups["servers"][1]].ansible_host }}'
