- name: setup networks and 2 vms
  vars:
    ostack_cloud: lard
    ipalias_network_name: ipalias
  hosts: localhost
  gather_facts: false

  roles:
    - role: networks
    - role: vm # in A
      vars:
        ostack_key_name: louiseo-yubikey # replace with your ssh key
        name_stuff: lard-a 
        availability_zone: ext-a
        vm_ip: '{{ hostvars[groups["servers"][0]].ansible_host }}'
    - role: vm # in B
      vars:
        ostack_key_name: louiseo-yubikey  # replace with your ssh key
        name_stuff: lard-b 
        availability_zone: ext-b
        vm_ip: '{{ hostvars[groups["servers"][1]].ansible_host }}'
