---
- name: Rejoin
  hosts: servers
  remote_user: ubuntu
  vars:
    # provide via cmd '-e primary=... -e standby=...'
    primary: # Old primary host that went down
    standby: # Old standby that will be promoted to primary
  tasks:
    - name: Perform IP switchover
      ansible.builtin.include_role:
        name: ostack
        tasks_from: move_floating_ip.yml
        apply:
          delegate_to: localhost
      vars:
        ostack_primary: "{{ primary }}"
        ostack_standby: "{{ standby }}"
      tags: promote

    - name: Repmgr
      ansible.builtin.include_role:
        name: rejoin
        tasks_from: promote.yml
      when: inventory_hostname == standby
      tags: promote

    - name: Rejoin old primary
      ansible.builtin.include_role:
        name: rejoin
        tasks_from: rejoin.yml
      vars:
        rejoin_new_primary_ip: "{{ hostvars[standby].ansible_host }}"
      when: inventory_hostname == primary
      tags: rejoin
