---
- name: Rejoin
  hosts: "{{ rejoin }}"
  remote_user: ubuntu
  vars:
    # Old primary host that went down
    rejoin: # provide via cmd
    # New primary host after it was promoted
    primary: # provide via cmd

  roles:
    - role: rejoin
      vars:
        rejoin_primary_ip: "{{ hostvars[primary].ansible_host }}"
