---
- name: Switch the primary and standby / replica
  hosts: localhost
  gather_facts: false
  remote_user: ubuntu
  # TODO: this can be probably done automatically if there are only two VMs?
  vars:
    primary: # provide via cmd '-e primary=...'
    standby: # provide via cmd '-e standby=...'
    # pre_tasks:
    #   - name: Find server role
  roles:
    - role: switchover
      vars:
        switchover_primary: "{{ primary }}"
        switchover_standby: "{{ standby }}"
