---
- name: Switch the primary and standby / replica
  hosts: "{{ standby }}"
  gather_facts: false
  remote_user: ubuntu
  vars:
    primary: # provide via cmd
    standby: # provide via cmd

  roles:
    - role: switchover
      switchover_primary: "{{ primary }}"

- name: Move floating IP to new primary
  hosts: localhost
  gather_facts: false
  vars:
    primary: # provide via cmd
    standby: # provide via cmd
    fip: # provide via cmd

  tasks:
    - name: Perform IP switchover
      ansible.builtin.include_role:
        name: ostack
        tasks_from: move_floating_ip.yml
      vars:
        ostack_primary: "{{ primary }}"
        ostack_standby: "{{ standby }}"
        ostack_floating_ip: "{{ fip }}"
