---
- name: Switch the primary and standby / replica
  hosts: servers
  gather_facts: false
  remote_user: ubuntu
  # TODO: this can be probably done automatically if there are only two VMs?
  vars:
    primary: # provide via cmd
    standby: # provide via cmd
  # pre_tasks:
  #   - name: Find server role

  tasks:
    - name: Switchover
      ansible.builtin.include_role:
        name: switchover
      when: inventory_hostname == standby
      vars:
        switchover_primary: "{{ primary }}"

- name: Move floating IP to new primary
  hosts: localhost
  gather_facts: false
  vars:
    primary: # provide via cmd
    standby: # provide via cmd

  tasks:
    - name: Perform IP switchover
      ansible.builtin.include_role:
        name: ostack
        tasks_from: move_floating_ip.yml
      vars:
        ostack_primary: "{{ primary }}"
        ostack_standby: "{{ standby }}"
