---
- name: Switch the primary and standby / replica
  hosts: servers
  gather_facts: false
  remote_user: ubuntu
  # TODO: this can be probably done automatically if there are only two VMs?
  # pre_tasks:
  #   - name: Find server role
  vars:
    # provide via cmd '-e primary=... -e standby=...'
    primary:
    standby:
  roles:
    - role: switchover
      vars:
        switchover_primary: "{{ primary }}"
        switchover_standby: "{{ standby }}"
